### PR TITLE
test only passes with Flow disabled

### PR DESCRIPTION
**Pull request by nnutter**
We recently started setting `WF_USE_FLOW=1` for our `apipe-tester` user which
caused Workflow tests to start failing.  This disables
`WF_USE_FLOW` in the two tests that started failing.

### CODE REVIEW

**Comment by brummett** [comment]
+1

But shouldn't the whole Workflow test suite run with ```WF_USE_FLOW=0```?  Except for maybe a test to ensure Flow is used instead of Workflow when ```WF_USE_FLOW=1```

**Comment by nnutter** [comment]
> But shouldn't the whole Workflow test suite run with WF_USE_FLOW=0? Except for maybe a test to ensure Flow is used instead of Workflow when WF_USE_FLOW=1

Maybe?  Probably?  Maybe once on both?

**Comment by mkiwala** [comment]
> But shouldn't the whole Workflow test suite run with WF_USE_FLOW=0? Except for maybe a test to ensure Flow is used instead of Workflow when WF_USE_FLOW=1

It depends on what the goal is.  The goal may be to use Flow in production exclusively, sometimes, or never.  Shouldn't we test with Flow when Flow would be used in production?

**Comment by mkiwala** [comment]
> It depends on what the goal is. The goal may be to use Flow in production exclusively, sometimes, or never. Shouldn't we test with Flow when Flow would be used in production?

Though in the context of Workflow, though, I guess just testing the compatibility (as @brummett suggests) seems sufficient.

**Comment by nnutter** [comment]
Let's move the `WF_USE_FLOW` discussion to [AR-974](https://jira.gsc.wustl.edu/browse/AR-974).

**Pull request merged**
